## 1.2. Phyton scikit-learn library for machine learning

### Scikit-Learn Library

In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
type(load_breast_cancer())

sklearn.utils._bunch.Bunch

In [5]:
data=load_breast_cancer()

In [6]:
pd.DataFrame(data['data'])

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [7]:
pd.DataFrame(data['target'])

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [8]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [9]:
from sklearn.model_selection import train_test_split

help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.

    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        com

In [10]:
len(data.data)

569

In [11]:
# train_test_split

In [12]:
569*0.75   #75% of the data for training

426.75

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

In [15]:
print(len(X_train))

426


In [16]:
569*0.25 #25% for testing

142.25

In [17]:
len(X_test)

143

In [18]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

data=load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, random_state=42)

model = DecisionTreeClassifier(criterion='entropy')
model

DecisionTreeClassifier(criterion='entropy')

In [19]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [20]:
pred=model.predict(X_test)

In [21]:
pred_2d=pred.reshape(len(pred), 1)

In [22]:
pred_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [23]:
import numpy as np

In [24]:
y_test_2d=y_test.reshape(len(pred), 1)

In [25]:
df1=pd.DataFrame(pred_2d, columns=['pred'])

In [26]:
df2=pd.DataFrame(y_test_2d, columns=['real'])

In [27]:
pd.concat([df1, df2], axis=1)

pred  real
0       1     1
1       0     0
2       0     0
3       1     1
4       1     1
..    ...   ...
138     1     1
139     0     0
140     1     1
141     0     0
142     1     1

[143 rows x 2 columns]

In [28]:
pd_concat = pd.concat([df1, df2], axis=1)

In [29]:
pd_concat.columns

Index(['pred', 'real'], dtype='object')

In [30]:
pd_concat

pred  real
0       1     1
1       0     0
2       0     0
3       1     1
4       1     1
..    ...   ...
138     1     1
139     0     0
140     1     1
141     0     0
142     1     1

[143 rows x 2 columns]

In [31]:
pd_concat[pd_concat['pred'] == pd_concat['real']]

pred  real
0       1     1
1       0     0
2       0     0
3       1     1
4       1     1
..    ...   ...
138     1     1
139     0     0
140     1     1
141     0     0
142     1     1

[137 rows x 2 columns]

In [32]:
len(pd_concat[pd_concat['pred'] == pd_concat['real']])

137

In [33]:
137/143

0.958041958041958

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler=StandardScaler()

In [36]:
X_train

array([[1.289e+01, 1.312e+01, 8.189e+01, ..., 5.366e-02, 2.309e-01,
        6.915e-02],
       [1.340e+01, 2.052e+01, 8.864e+01, ..., 2.051e-01, 3.585e-01,
        1.109e-01],
       [1.296e+01, 1.829e+01, 8.418e+01, ..., 6.608e-02, 3.207e-01,
        7.247e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]])

In [37]:
df_scale_previous=pd.DataFrame(data['data'])

In [38]:
scaler.fit(X_train)

StandardScaler()

In [39]:
X_train=scaler.transform(X_train)

In [40]:
df_scale_after=pd.DataFrame(X_train)

In [41]:
df_scale_previous

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [42]:
df_scale_after

0         1         2         3         4         5         6   \
0   -0.349138 -1.438513 -0.411726 -0.390479 -1.863662 -1.268607 -0.826171   
1   -0.204687  0.312640 -0.133673 -0.275880  1.078073  0.863546  0.726314   
2   -0.329312 -0.215072 -0.317394 -0.364357 -1.579880 -0.457451 -0.597310   
3    1.027403  2.089824  1.046922  0.917584  0.316303  0.562037  1.048527   
4    1.828969  0.696001  1.763681  1.783821 -0.333674  0.628175  0.974660   
..        ...       ...       ...       ...       ...       ...       ...   
421 -1.482661 -1.078817 -1.363286 -1.154195  0.162946  0.984150 -0.017962   
422 -0.703187 -0.205607 -0.688544 -0.680910  1.336057 -0.015692 -0.213582   
423  0.047396 -0.562937 -0.065292 -0.062691 -2.240606 -1.473633 -1.021664   
424 -0.040408  0.099662 -0.031514 -0.155663  0.748426  0.209953  0.320044   
425 -0.550238  0.312640 -0.604098 -0.551143 -1.105476 -1.208500 -0.810506   

           7         8         9   ...        20        21        22  \
0   -0.952866 -1.729368 -0.941541  ... -0.542685 -1.655655 -0.589864   
1    0.898441  1.178770  1.474377  ...  0.041487  0.689899  0.194128   
2   -0.764588  0.275343 -0.501024  ... -0.435901 -0.148985 -0.320159   
3    0.930437 -0.325697 -0.477474  ...  1.113515  2.165006  1.165793   
4    1.265740 -0.131572 -1.713139  ...  1.471556  0.387568  1.556276   
..        ...       ...       ...  ...       ...       ...       ...   
421 -0.503063  0.379872  3.767006  ... -1.356547 -1.634059 -1.341770   
422 -0.340964  0.002822  0.359231  ... -0.643188  0.623452 -0.647074   
423 -1.097247 -1.090996 -1.225522  ... -0.272584 -0.806803 -0.376764   
424  0.446522 -0.489956  0.392478  ...  0.173397  0.879270  0.212290   
425 -0.794470 -0.228635 -0.808555  ... -0.601311  1.218146 -0.675225   

           23        24        25        26        27        28        29  
0   -0.525560 -1.510669 -0.891500 -0.750217 -0.916711 -0.925086 -0.808411  
1   -0.051934  1.129415  0.923942  1.222217  1.436560  1.149559  1.569111  
2   -0.446032 -1.634396 -0.106752 -0.539891 -0.723713  0.534970 -0.619348  
3    0.997696  0.383604  0.860948  1.872819  1.310691  0.152884  0.421636  
4    1.385595 -0.577759  0.296680  0.595768  1.232995  0.050452 -1.406351  
..        ...       ...       ...       ...       ...       ...       ...  
421 -1.043821 -0.452739 -0.027674 -0.625430 -1.006838 -1.014510  1.426745  
422 -0.623509  1.620874  0.122440  0.098634  0.142137 -0.117015  0.434165  
423 -0.334976 -1.962898 -1.322676 -1.152453 -1.232624 -0.682827 -1.261137  
424 -0.007830  1.297546  0.730938  0.700428  1.088480  0.489445  1.261600  
425 -0.577280 -0.814867 -1.066276 -0.770847 -0.595824 -0.299115 -0.829481  

[426 rows x 30 columns]

In [43]:
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

print(X_train)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

X_train

[[1.497e+01 1.695e+01 9.622e+01 ... 8.485e-02 2.404e-01 6.428e-02]
 [1.193e+01 2.153e+01 7.653e+01 ... 7.247e-02 2.438e-01 8.541e-02]
 [1.317e+01 1.822e+01 8.428e+01 ... 1.045e-01 2.235e-01 6.925e-02]
 ...
 [1.375e+01 2.377e+01 8.854e+01 ... 6.106e-02 2.663e-01 6.321e-02]
 [1.382e+01 2.449e+01 9.233e+01 ... 1.521e-01 3.651e-01 1.183e-01]
 [1.910e+01 2.629e+01 1.291e+02 ... 1.841e-01 2.311e-01 9.203e-02]]


array([[ 0.24182184, -0.51812217,  0.18045397, ..., -0.43214156,
        -0.74498349, -1.05652086],
       [-0.61792541,  0.53361457, -0.62933706, ..., -0.62218729,
        -0.69169127,  0.08902726],
       [-0.26723903, -0.22648338, -0.31060265, ..., -0.13049386,
        -1.00987714, -0.7870758 ],
       ...,
       [-0.10320831,  1.04800111, -0.13540154, ..., -0.79734252,
        -0.33902222, -1.11453016],
       [-0.0834115 ,  1.21333963,  0.02046986, ...,  0.60021507,
         1.2095868 ,  1.87213553],
       [ 1.40983373,  1.62668595,  1.53271041, ...,  1.09144797,
        -0.89075336,  0.44792591]])

In [44]:
print(X_test)

X_test = scaler.fit_transform(X_test)

X_test

[[1.286e+01 1.332e+01 8.282e+01 ... 1.155e-01 2.382e-01 8.553e-02]
 [2.047e+01 2.067e+01 1.347e+02 ... 1.613e-01 3.220e-01 6.386e-02]
 [1.262e+01 1.715e+01 8.062e+01 ... 9.851e-02 3.270e-01 7.330e-02]
 ...
 [1.298e+01 1.935e+01 8.452e+01 ... 9.858e-02 3.596e-01 9.166e-02]
 [1.347e+01 1.406e+01 8.732e+01 ... 1.335e-01 3.227e-01 9.326e-02]
 [1.705e+01 1.908e+01 1.134e+02 ... 2.543e-01 3.109e-01 9.061e-02]]


array([[-0.37520375, -1.51240336, -0.39552177, ..., -0.05804146,
        -1.05978225,  0.06279197],
       [ 1.81427953,  0.27532415,  1.75168819, ...,  0.62546103,
         0.46434552, -1.22812819],
       [-0.44425447, -0.58083923, -0.48657539, ..., -0.31159402,
         0.55528393, -0.66577072],
       ...,
       [-0.34067839, -0.04573711, -0.32516215, ..., -0.31054937,
         1.14820237,  0.4279669 ],
       [-0.19969984, -1.33241447, -0.20927572, ...,  0.21058397,
         0.4770769 ,  0.52328172],
       [ 0.83030675, -0.11140874,  0.87012358, ...,  2.01335911,
         0.26246225,  0.36541654]])