## 1.4. Data pre-processing for making a good training data set

### Missing value processing

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
import pandas as pd

In [4]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris_df = pd.DataFrame(iris['data'],
             columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width'])

In [6]:
iris_df.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width'], dtype='object')

In [7]:
iris_df['Sepal_Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal_Length, Length: 150, dtype: float64

In [8]:
import numpy as np

In [9]:
np.mean(iris_df['Sepal_Length'])

5.843333333333334

In [10]:
data=[[1.0,2.0,3.0,4.0],[5.0,6.0,np.nan,8.0],[10.0,11.0,12.0,np.nan]]

In [11]:
np.array(data)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [12]:
pd.DataFrame(np.array(data), columns=['A','B','C','D'])

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [13]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [14]:
df.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [15]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [16]:
df.dropna()

A    B    C    D
0  1.0  2.0  3.0  4.0

In [17]:
df.dropna(inplace=True)

In [18]:
df

A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [20]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [21]:
df.dropna(axis=1, inplace=True)

In [22]:
df

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [23]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [24]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [25]:
df.loc[3]=[np.nan,np.nan,np.nan,np.nan]

In [26]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN
3   NaN   NaN   NaN  NaN

In [27]:
df.dropna(how='all', inplace=True)

In [28]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [29]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])
df.loc[3]=[np.nan,np.nan,np.nan,3]

In [30]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN
3   NaN   NaN   NaN  3.0

In [31]:
df.dropna(thresh=3, inplace=True)

In [32]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [33]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [34]:
df.dropna(subset=['C'], inplace=True)

In [35]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [36]:
from sklearn.impute import SimpleImputer

In [37]:
df=pd.DataFrame(np.array(data), columns=['A','B','C','D'])

In [38]:
impt=SimpleImputer(missing_values=np.nan, strategy='mean')

In [39]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [40]:
help(impt.fit)

Help on method fit in module sklearn.impute._base:

fit(X, y=None) method of sklearn.impute._base.SimpleImputer instance
    Fit the imputer on `X`.

    Parameters
    ----------
    X : {array-like, sparse matrix}, shape (n_samples, n_features)
        Input data, where `n_samples` is the number of samples and
        `n_features` is the number of features.

    y : Ignored
        Not used, present here for API consistency by convention.

    Returns
    -------
    self : object
        Fitted estimator.



In [41]:
imputed=impt.fit(df.values)

In [42]:
imputed.transform(df.values)

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [43]:
(3+12)/2

7.5

In [44]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

In [45]:
df

0   1     2       3
0  green   M  10.1  class2
1    red   L  13.5  class1
2   blue  XL  15.3  class2

In [46]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

In [47]:
df.columns=['color', 'size', 'price', 'classlabel']

In [48]:
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [49]:
df['size']

0     M
1     L
2    XL
Name: size, dtype: object

In [50]:
df['size']=df['size'].map(size_mapping)

In [ ]:
df['size']

0    1
1    2
2    3
Name: size, dtype: int64

In [52]:
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [53]:
df['classlabel']

0    class2
1    class1
2    class2
Name: classlabel, dtype: object

In [54]:
df['classlabel'].value_counts()

classlabel
class2    2
class1    1
Name: count, dtype: int64

In [55]:
np.unique(df['classlabel'])

array(['class1', 'class2'], dtype=object)

In [56]:
enumerate(np.unique(df['classlabel']))

In [57]:
for idx, label in enumerate(np.unique(df['classlabel'])):
    print(idx, label)

0 class1
1 class2


In [ ]:
{label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

{'class1': 0, 'class2': 1}

In [59]:
class_mapping={label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [60]:
df['classlabel']=df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [61]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])
df.columns=['color', 'size', 'price', 'classlabel']

In [62]:
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [63]:
from sklearn.preprocessing import LabelEncoder

In [64]:
enc=LabelEncoder()

In [65]:
y=enc.fit_transform(df['classlabel'].values)

In [66]:
y

array([1, 0, 1])

In [67]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
iris=pd.DataFrame(iris.target, columns=['species'])

In [69]:
iris

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

In [70]:
iris['species'].replace({0:'setosa', 1:'versicolor', 2:'virginica'}, inplace=True)

C:\Users\MGC MKW\AppData\Local\Temp\ipykernel_6568\1816291852.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris['species'].replace({0:'setosa', 1:'versicolor', 2:'virginica'}, inplace=True)


In [71]:
iris

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [72]:
pd.get_dummies(iris['species'])

setosa  versicolor  virginica
0      True       False      False
1      True       False      False
2      True       False      False
3      True       False      False
4      True       False      False
..      ...         ...        ...
145   False       False       True
146   False       False       True
147   False       False       True
148   False       False       True
149   False       False       True

[150 rows x 3 columns]

In [73]:
from sklearn.preprocessing import OneHotEncoder

In [74]:
onehot_encoder=OneHotEncoder()

In [75]:
len_iris=len(iris['species'])

In [76]:
np.array(iris['species'])

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [77]:
iris_species_2d=np.array(iris['species']).reshape(len_iris, 1)

In [78]:
onehot_encoder.fit_transform(iris_species_2d)

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [79]:
#Convert to a space matrix

In [80]:
onehot_reshaped=onehot_encoder.fit_transform(iris_species_2d)

In [81]:
print(onehot_reshaped[0:50])

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  (25, 0)	1.0
  (26, 0)	1.0
  (27, 0)	1.0
  (28, 0)	1.0
  (29, 0)	1.0
  (30, 0)	1.0
  (31, 0)	1.0
  (32, 0)	1.0
  (33, 0)	1.0
  (34, 0)	1.0
  (35, 0)	1.0
  (36, 0)	1.0
  (37, 0)	1.0
  (38, 0)	1.0
  (39, 0)	1.0
  (40, 0)	1.0
  (41, 0)	1.0
  (42, 0)	1.0
  (43, 0)	1.0
  (44, 0)	1.0
  (45, 0)	1.0
  (46, 0)	1.0
  (47, 0)	1.0
  (48, 0)	1.0
  (49, 0)	1.0


In [82]:
print(onehot_reshaped[50:100])

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 1)	1.0
  (14, 1)	1.0
  (15, 1)	1.0
  (16, 1)	1.0
  (17, 1)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 1)	1.0
  (22, 1)	1.0
  (23, 1)	1.0
  (24, 1)	1.0
  (25, 1)	1.0
  (26, 1)	1.0
  (27, 1)	1.0
  (28, 1)	1.0
  (29, 1)	1.0
  (30, 1)	1.0
  (31, 1)	1.0
  (32, 1)	1.0
  (33, 1)	1.0
  (34, 1)	1.0
  (35, 1)	1.0
  (36, 1)	1.0
  (37, 1)	1.0
  (38, 1)	1.0
  (39, 1)	1.0
  (40, 1)	1.0
  (41, 1)	1.0
  (42, 1)	1.0
  (43, 1)	1.0
  (44, 1)	1.0
  (45, 1)	1.0
  (46, 1)	1.0
  (47, 1)	1.0
  (48, 1)	1.0
  (49, 1)	1.0


In [83]:
print(onehot_reshaped[100:150])

  (0, 2)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (4, 2)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
  (8, 2)	1.0
  (9, 2)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 2)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 2)	1.0
  (17, 2)	1.0
  (18, 2)	1.0
  (19, 2)	1.0
  (20, 2)	1.0
  (21, 2)	1.0
  (22, 2)	1.0
  (23, 2)	1.0
  (24, 2)	1.0
  (25, 2)	1.0
  (26, 2)	1.0
  (27, 2)	1.0
  (28, 2)	1.0
  (29, 2)	1.0
  (30, 2)	1.0
  (31, 2)	1.0
  (32, 2)	1.0
  (33, 2)	1.0
  (34, 2)	1.0
  (35, 2)	1.0
  (36, 2)	1.0
  (37, 2)	1.0
  (38, 2)	1.0
  (39, 2)	1.0
  (40, 2)	1.0
  (41, 2)	1.0
  (42, 2)	1.0
  (43, 2)	1.0
  (44, 2)	1.0
  (45, 2)	1.0
  (46, 2)	1.0
  (47, 2)	1.0
  (48, 2)	1.0
  (49, 2)	1.0


In [84]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
                      header=None)

In [85]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

In [86]:
df_wine

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0              1    14.23        1.71  2.43               15.6        127   
1              1    13.20        1.78  2.14               11.2        100   
2              1    13.16        2.36  2.67               18.6        101   
3              1    14.37        1.95  2.50               16.8        113   
4              1    13.24        2.59  2.87               21.0        118   
..           ...      ...         ...   ...                ...        ...   
173            3    13.71        5.65  2.45               20.5         95   
174            3    13.40        3.91  2.48               23.0        102   
175            3    13.27        4.28  2.26               20.0        120   
176            3    13.17        2.59  2.37               20.0        120   
177            3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [87]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test =\
    train_test_split(X, y,
                    test_size=0.3,
                    random_state=0,
                    stratify=y)

In [88]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
x_train_norm = mms.fit_transform(X_train)
x_test_nrom = mms.transform(X_test)

In [89]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
x_train_std = stdsc.fit_transform(X_train)
x_test_std = stdsc.transform(X_test)

In [90]:
from sklearn.preprocessing import RobustScaler
rbs = RobustScaler()
x_train_robust = rbs.fit_transform(X_train)
x_test_robust = rbs.transform(X_test)

In [91]:
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()
x_train_maxabs = mas.fit_transform(X_train)
x_test_maxabs = mas.transform(X_test)