Array Transposition

In [3]:
import numpy as np

In [4]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [6]:
arr=np.random.randn(6,3)
arr

array([[ 0.54557415, -0.55238451, -2.30041282],
       [ 1.18932415,  0.11555787, -1.96069306],
       [ 0.41737546, -1.47646071, -0.02081591],
       [-1.05574735, -0.02369544, -0.33869621],
       [-1.20353947,  0.17024086,  0.8237337 ],
       [ 1.15827565,  0.45461322, -0.23055475]])

In [7]:
np.dot(arr.T, arr)

array([[ 5.79105758, -0.43347719, -4.49649777],
       [-0.43347719,  2.73463511,  1.11831824],
       [-4.49649777,  1.11831824,  9.98305754]])

In [8]:
arr=np.arange(16).reshape(2,2,4)

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [21]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])